### ISSUE TITLE
Problem with Variables

### ISSUE THREAD

**Issue by pedrocesar-ti** [pedrocesar-ti/internet-speedtest-docker#1]
Environment variables it's not working properly.

**Comment by jeffprandall** [comment]
Any updates on this?

**Comment by pedrocesar-ti** [comment]
Jeff.. Sorry I couldnt stop to fix it until now..

**Comment by pedrocesar-ti** [comment]
I just saw, a problem with a variable that give username and password. Turn around would be use username admin password **pedrocesar**. Tell me if this work.

**Comment by pedrocesar-ti** [comment]
#3

**Comment by pedrocesar-ti** [comment]
#3 probably will solve the problem @jeffprandall.

**Comment by pedrocesar-ti** [comment]
Solved by @MTRNord in the PR #3 .

**Comment by chan-vince** [comment]
This did not fix the login problem for me. I think the issue is in the Dockerfile for speedweb:

`ADD conf/grafana.db /var/lib/grafana/grafana.db`

This is your grafana.db in `internet-speedtest-docker/speedweb/conf/` which gets built into the image. Therefore your login admin/pedrocesar is actually built into the docker image. Setting the environment variables such as GF_SECURITY_ADMIN_PASSWORD doesn't have any effect as your admin user is already created in your grafana.db.

I created another Docker container but with volume mounts so it created a new grafana.db. I can confirm that doing this creates a new user as GF_SECURITY_ADMIN_PASSWORD has effect.

**Comment by attarchi** [comment]
This issue is solved in Fix #28
